import { getSession, withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import { useContext, useEffect } from "react";
import Navbar from "../components/Navbar";
import Todo from "../components/Todo";
import TodoForm from "../components/TodoForm";
import { TodosContext } from "../contexts/TodosContext";
import { minifyData, table } from "../utils/Airtable";

export default function Home({ initialTodos, user }) {
	const { todos, setTodos } = useContext(TodosContext);

	useEffect(() => setTodos(initialTodos), []);
	return (
		<div>
			<Head>
				<title>JAMStack - Todo</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Navbar user={user} />
				<TodoForm />
				<ul>
					{todos.map(todo => (
						<Todo key={todo.id} todo={todo} />
					))}
				</ul>
			</main>
		</div>
	);
}
export const getServerSideProps = withPageAuthRequired({
	async getServerSideProps(context) {
		const { user } = getSession(context.req, context.res);
		const todos = await table
			.select({ filterByFormula: `userId="${user.sub}"` })
			.firstPage();
		return {
			props: { initialTodos: todos.map(todo => minifyData(todo)), user },
		};
	},
});
